/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shaddock_libcurl_Curl */

#ifndef _Included_com_shaddock_libcurl_Curl
#define _Included_com_shaddock_libcurl_Curl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shaddock_libcurl_Curl
 * Method:    maintest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shaddock_libcurl_Curl_maintest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
